services:
  db:
    image: postgres:16
    container_name: local-pg
    ports:
      - "${PG_HOST_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${PG_DB:-university}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres} -d ${PG_DB:-university}"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata_local:
